name: salmon-rnaseq
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  # Core tools
  - sra-tools=3.1.1        # provides prefetch, fasterq-dump, etc.
  - salmon=1.10.2          # transcript quantification
  - fastqc=0.12.1          # optional QC
  - multiqc=1.17           # summary reports