name: salmon-rnaseq
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - python=3.11        # ✅ pin Python to 3.11 (fastq-dl compatible)
  - fastq-dl           # download FASTQ files from SRA/ENA
  - salmon             # transcript quantification
  - fastqc             # optional QC
  - multiqc            # summary reports


