name: salmon-rnaseq
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - fastq-dl           # download FASTQ files from SRA/ENA
  - salmon             # transcript quantification
  - fastqc             # optional QC
  - multiqc            # summary reports



